services:
  app:
    image: openjdk:22
    container_name: bot_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      FB_SECRET: "56062c02db306aad86835dfa697e97c8"
      GG_SECRET: "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"
      GH_SECRET: "846d764cafe7a8b0a58c256ba7f4f2b51e48032a"
      JWT_SIGNERKEY: "25+NtacDbdc1Rj6bRi/CwfVDxST13uiybHAkpk6kfXNJ08aAqUgV2xdA3xzYuJMi"
      PG_PW: Abc123
      PG_USER: dt313
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "./mvnw spring-boot:run"]

  db:
    image: postgres
    container_name: bot-db
    environment:
      POSTGRES_PASSWORD: Abc123  # Mật khẩu cho user postgres
      POSTGRES_USER: dt313        # Tạo user dt313
      POSTGRES_DB: bot           # Tạo database bot
    ports:
      - "5432:5432"  # Cổng mặc định cho PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data: {}
  redis_data: {}
