server:
  port: 8080
client:
  domain: "http://web-dev.com:3000"



spring:
  web:
    resources:
      static-locations: file:/uploads/images/

  application:
    name: api

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "958297514464-nocdv0v1q0rbqhacir1cf6lo6vidt7pi.apps.googleusercontent.com"
            client-secret: ${GG_SECRET}
            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            scope:
              - profile
              - email
          github:
            clientId: "Ov23lik6O13NyVLk7W18"
            clientSecret: ${GH_SECRET}
            redirect-uri: "http://localhost:8080/oauth2/callback/github"
          facebook:
            clientId: "870226731637000"
            clientSecret: ${FB_SECRET}
            scope:
              - profile
            redirect- uri: "http://localhost:8080/login/oauth2/code/facebook"





  datasource:
    url: "jdbc:oracle:thin:@127.0.0.1:1521:xe"
    username: ${ORACLE_USER}
    password: ${ORACLE_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



jwt:
  valid-duration: 36000
  refreshable-duration: 360000