server:
  port: 8080
  domain: "http://localhost:8080/api/v1"

client:
  domain: "http://web-deb.com:3000"

spring:

  data:
    redis:
      host: "127.0.0.1"
      port: 6379

  web:
    resources:
      static-locations: file:/uploads/images/

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "tuanbon21313@gmail.com"
    password: "ffdy mbmg zwey zzgc"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable : true





  application:
    name: api

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "958297514464-nocdv0v1q0rbqhacir1cf6lo6vidt7pi.apps.googleusercontent.com"
            client-secret: ${GG_SECRET}
            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            scope:
              - profile
              - email
          github:
            clientId: "Ov23lik6O13NyVLk7W18"
            clientSecret: ${GH_SECRET}
            redirect-uri: "http://localhost:8080/oauth2/callback/github"
          facebook:
            clientId: "870226731637000"
            clientSecret: ${FB_SECRET}
            scope:
              - profile
            redirect- uri: "http://localhost:8080/login/oauth2/code/facebook"





  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:xe"
    username: ${ORACLE_USER}
    password: ${ORACLE_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true





jwt:
  signerKey: "by3A3pE0Xi35UmiCMaTxUiGP80OkIyedn3F4v4ke4O2XPu/MXK57FanVqhUTpZ7y"
  valid-duration: 20
  refreshable-duration: 3600
  reset-password-key: "OeHwueSNJEm6+qCtMk8F/VJFfIUjuPVTgKChBKEd2QhwRhAqZYBdJi3nxl0nldWg"
  reset-password-duration: 300
