server:
  port: 8080
  domain: ${PROD_SERVER_DOMAIN}
client:
  domain: ${PROD_CLIENT_DOMAIN}
spring:

  ai:
    ollama:
      base-url: http://127.0.0.1:11434/api/chat
      chat:
        options:
          model: llama3.2

  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: 6379
  web:
    resources:
      static-locations: file:/uploads/images/

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${PROD_GMAIL_USER}
    password: ${PROD_GMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable : true





  application:
    name: "blog-prod-api"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${PROD_GG_ID}
            client-secret: ${PROD_GG_SECRET}
            redirect-uri: ${PROD_SERVER_ORIGIN}/oauth2/callback/google
            scope:
              - profile
              - email
          github:
            clientId: ${PROD_GH_ID}
            clientSecret: ${PROD_GH_SECRET}
            redirect-uri: ${PROD_SERVER_ORIGIN}/oauth2/callback/github
          facebook:
            clientId: ${PROD_FB_ID}
            clientSecret: ${PROD_FB_SECRET}
            scope:
              - profile
            redirect- uri: ${PROD_SERVER_ORIGIN}/oauth2/code/facebook





  datasource:
    url: jdbc:${PROD_PG_URL}
    username: ${PROD_PG_USER}
    password: ${PROD_PG_PW}

    hikari:
      auto-commit: false


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true





jwt:
  signerKey: ${PROD_REFRESH_KEY}
  valid-duration: 3600
  refreshable-duration: 86400
  reset-password-key: ${PROD_SIGNER_KEY}
  reset-password-duration: 300
